### ISSUE TITLE
Possible bug in __get_ngraph_features

### ISSUE THREAD

**Issue by iamsimha** [bmitra-msft/NDRM#1]
In the function ```__get_ngraph_features: ``` present in Duet.ipynb
```python 
for i in range(token_len):
    for j in range(0, self.max_ngraph_len):
          if i+j < token_len:
                ....
```
It seems to me that range should be from (1,  self.max_ngraph_len + 1)

**Comment by bhaskar-mitra** [comment]
The ngraph index is zero based. Check the following statement in the __load_ngraphs method.

```
                self.ngraphs[row[0]] = int(row[1]) - 1
```

Hope this helps.

Best regards,
Bhaskar

**Comment by iamsimha** [comment]
Thanks for the reply. But I still don't get it
```Python
for i in range(token_len):
    for j in range(0, self.max_ngraph_len):
        if i+j < token_len:
            # Buggy Line
            ngraph_idx = self.ngraphs.get(token[i:i+j]) 
            if ngraph_idx != None:
                if doc_idx == 0:
                        features_query[sample_idx, ngraph_idx, w_idx] += 1
                 else:
                        features_docs[sample_idx, doc_idx-1, ngraph_idx, w_idx] += 1
```
In the first iteration j = 0, so ```token[i:i+j]``` will always be an empty string. In the last iteration j = self.max_ngraph_len - 1, therefore the maximum length token will be  self.max_ngraph_len - 1 and not self.max_ngraph_len and we will miss out the maximum length n-gram.

**Comment by bhaskar-mitra** [comment]
Sorry, for my hasty response. You are right. That's a bug. I will fix it soon. Thanks for reporting it!

Cheers!

**Comment by aliahmedghazi** [comment]
Can you provide format for input files ?

**Comment by bhaskar-mitra** [comment]
@iamsimha Sorry, I just realised that I had forgotten to push the fix. It's done [now](https://github.com/bmitra-msft/NDRM/commit/ff57cfe27290e65592449743b917b8d61f1e8116).

@aliahmedghazi The "Data reader" section in the notebook describes the input formats. Is that what you are looking for?
